### ISSUE TITLE
Did these boards work out? Have you tried them yet?

### ISSUE THREAD

**Issue by ned-pcs** [AnttiNykanen/stm32_nucleo-144_proto_shield#1]
They look interesting, but I'd like to know whether they're correct.

**Comment by AnttiNykanen** [comment]
That's an excellent question. I never got around to actually trying them and I'm not really set up to do so at the moment.

Do you want to try them out? I can send a couple your way (you'll have to provide your own pin headers). If you want them, drop me an e-mail at aon@iki.fi so we can work out the details...
